   - name: 'Update APT package manager'
     apt:
       update_cache: yes

   - name: 'Install aws cli'
     shell: sudo apt update -y && sudo apt install curl unzip -y && curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip" && unzip awscliv2.zip && sudo ./aws/install

   - name: 'Run jenkins script'
     shell: chmod +x Install.sh && ./Install.sh

   - name: 'Ensure jenkins is running'
     service: name=jenkins state=started

   - name: 'Remove .jenkins'
     shell: rm -r -f ~/.jenkins
     become_user: jenkins

   - name: 'Waiting for ssh access'
     command: /bin/sleep 50
     async: 50
